fix: 전체 오류 수정
SangmokKIM1994/community-server pull request #54
Opened 2023-03-01 19:11 UTC by Ryeonjoo

2023-03-01 23:57 UTC, SangmokKIM1994 reviewed
확인했습니당

2023-03-02 00:14 UTC, minenam requested changes

2023-03-02 00:14 UTC, minenam commented on api/controllers/users.controller.js
> +    const nickname = req.quert.nickname;
req.query 오타 같아요!

2023-03-02 00:18 UTC, SangmokKIM1994 reviewed
확인이요

2023-03-02 00:30 UTC, Ryeonjoo commented on api/controllers/users.controller.js
> +    const nickname = req.quert.nickname;
수정했습니다

2023-03-02 00:33 UTC, closed without merging